---
data:
    root: /cloud_computing
    validation_txt: ./data_path/validation.txt
    training_txt: ./data_path/training.txt

constant:
  time_horizon: 6
  obs_steps: 50
  pred_steps: 60
  total_steps: 110

vae:
  epochs: 100
  kld_weight: 0.00025
  LR: 0.00005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  latent_dim: 256
  in_channels: 300

plot:
    bg:
        color: '#FFFFFF'
    lane: 
        color: '#0A1931' 
        lw: 1
        alpha: 0.9
    lane_polygon: 
        color: dimgray
        lw: 1.5
        alpha: 0.9
    crosswalk_polygon:
        color: darkorange
    neighbor:
        fc: '#5389FF'
        ec: '#0814ff'
    agent:
        fc: '#73CEB3'
        ec: 'green'
    history: 
        color: green
        lw: 2.0
    gt: 
        color: green
        lw: 5.0
        alpha: 0.6
    goal:
        color: gold
        lw: 2.0
        alpha: 1
    traj: 
        color: crimson
        lw: 2.0
        alpha: 1
